# Generated by Django 5.0.6 on 2024-07-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('developer', 'Developer'), ('driver', 'Driver'), ('manager', 'Manager'), ('administration', 'Administration')], default='client', max_length=20),
        ),
    ]
