# Generated by Django 5.0.6 on 2024-07-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_supermarket_schema_name_tokenmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supermarket',
            new_name='Tenant',
        ),
    ]
