# Generated by Django 5.0.6 on 2024-07-13 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 13, 33, 12, 265184, tzinfo=datetime.timezone.utc)),
        ),
    ]
