# Generated by Django 5.0.6 on 2024-07-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_supermarket_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supermarket',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supermarket',
            new_name='tenant',
        ),
    ]
